version: '3.8'
services:
  frontend:
    image: ghcr.io/naborisk/fullstack-todo-frontend:main
  backend:
    image: ghcr.io/naborisk/fullstack-todo-backend:main
    restart: always
    depends_on:
      - db
    environment:
      - 'PORT=3001'
      - 'DB_HOST=db'
  db:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=todo'
  nginx:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
