version: '3.8'
services:
  frontend:
    build: ./frontend
    # ports:
    #   - '3000:3000'
  backend:
    build: ./backend
    # ports:
    #   - '3001:3001'
    restart: always
    depends_on:
      - db
    environment:
      - 'PORT=3001'
      - 'DB_HOST=db'
  db:
    image: postgres
    # ports:
    #   - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=todo'
  nginx:
    image: nginx
    ports:
      - '80:80'
    # depends_on:
    #   - frontend
    #   - backend
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
