version: '3.8'
services:
  frontend:
    image: ghcr.io/naborisk/fullstack-todo-frontend:main
    ports:
      - '3000:3000'
  backend:
    image: ghcr.io/naborisk/fullstack-todo-backend:main
    ports:
      - '3001:3001'
    restart: always
    depends_on:
      - db
    environment:
      - 'PORT=3001'
      - 'DB_HOST=db'
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=todo'
