version: '3.8'
services:
  frontend:
    image: imbios/bun-node:21-debian
    working_dir: /frontend/
    volumes:
      - ./frontend/:/frontend/:rw
    command: >
      bash -c 'bun i && bun run dev'
  backend:
    image: rust:1.78-buster
    command: >
      bash -c 'cargo install cargo-watch && cargo watch -x run'
    restart: always
    working_dir: /backend/
    volumes:
      - ./backend/:/backend/:rw
    depends_on:
      - db
    environment:
      - 'PORT=3001'
      - 'DB_HOST=db'
  db:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=todo'
  nginx:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
